inherit_from: .rubocop_todo.yml
AllCops:
  # Caution! Setting this to 2.4 can cause issues with
  # rolling back to jruby 9.1.x.x which only supports 2.3
  # Its mainly just regex matchers. But we should wait until
  # we're happy on MRI.
  TargetRubyVersion: 2.4
