language: ruby
dist: xenial
services: mysql
bundler_args: "--without deployment"
cache:
  bundler: true
before_script:
- bundle exec rake db:setup
- bundle exec rake db:migrate
script:
- bundle exec rubocop
- bundle exec rspec
before_deploy: "./compile-build"
deploy:
  file: release.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: sanger/unified_warehouse
    tags: true
  provider: releases
  api_key:
    secure: ZliaLdfkU3OUFeMU3B3DlcIb7lLPSIYBjOHNbDmGE5NVxyof66H24mRq1aRqhH9OrVs1AY16nQ4E4ri9FT6JQPf0GzggNQ7b543YKMp7R8Omg7vZRiCxb1YG58EFRMf9vbATBNkvEHB+r2HhvV3F/rEpr4iuzvg9U+5it6gHp+Q=
