language: ruby
dist: xenial
services: mysql
# We don't specify a list of ruby versions, as Travis will fall back to .ruby-version
bundler_args: --without deployment
cache:
  bundler: true
before_script:
  - bundle exec rake db:setup
script:
  - bundle exec rubocop
  - bundle exec rspec


