language: ruby
dist: xenial
# We don't specify a list of ruby versions, as Travis will fall back to .ruby-version
bundler_args: --without deployment
cache:
  bundler: true
script:
  - bundle exec rubocop
  - bundle exec rspec


